/**
 * CycleOps ESP32 Controller — Configuration
 *
 * ⚠️  FILL IN YOUR VALUES BEFORE FLASHING ⚠️
 *
 * SECURITY:
 *   - Do NOT commit this file with real credentials to a public repository.
 *   - Add config.h to your .gitignore.
 *   - The CONTROLLER_AUTH_TOKEN is generated by `npm run db:seed` — save it.
 *
 * WIRING (verify against your specific washing machine before connecting):
 *   - RELAY_PIN connects to an opto-isolated relay module
 *   - Relay NO (normally open) contacts bridge the machine's start trigger
 *   - DO NOT connect relay directly to mains voltage without proper isolation
 *   - STATUS_LED_PIN is optional — connect an LED with 330Ω resistor to GND
 */

#pragma once

// ─── Wi-Fi ────────────────────────────────────────────────────────────────
#define WIFI_SSID       "YourWiFiNetworkName"
#define WIFI_PASSWORD   "YourWiFiPassword"

// ─── Backend API ──────────────────────────────────────────────────────────
// Production: "https://mvp.cycleops.app"
// Development (ngrok): "https://your-tunnel.ngrok.io"
#define API_BASE_URL    "https://mvp.cycleops.app"
#define API_HTTPS       true   // false = plain HTTP (dev only)

// ─── Controller Identity ──────────────────────────────────────────────────
// These values come from `npm run db:seed` — do NOT share or commit.
#define CONTROLLER_ID         "ctrl-washer-1"
#define CONTROLLER_AUTH_TOKEN "PASTE_YOUR_TOKEN_HERE"

// ─── Relay Configuration ──────────────────────────────────────────────────
// Default relay pulse duration (milliseconds).
// The backend can override this per-command (relayDurationMs in command payload).
#define RELAY_PIN             26          // GPIO26 — change to your wiring
#define RELAY_ACTIVE_HIGH     true        // true = relay activates on HIGH; false = active LOW
#define DEFAULT_RELAY_PULSE_MS 500        // 500ms default — tune after wiring test
#define MAX_RELAY_PULSE_MS    5000        // Hard cap — never hold relay longer than this

// ─── Status LED (optional) ────────────────────────────────────────────────
#define STATUS_LED_PIN        2           // GPIO2 = built-in LED on most ESP32 dev boards
#define STATUS_LED_ENABLED    true

// ─── Timing ───────────────────────────────────────────────────────────────
#define HEARTBEAT_INTERVAL_MS   30000     // 30 seconds
#define POLL_INTERVAL_MS         3000     // 3 seconds — poll for commands
#define WIFI_RETRY_DELAY_MS      5000     // Retry Wi-Fi every 5 seconds
#define API_TIMEOUT_MS           8000     // HTTP request timeout
#define REGISTER_RETRY_DELAY_MS 10000     // Retry registration every 10 seconds

// ─── Firmware ─────────────────────────────────────────────────────────────
#define FIRMWARE_VERSION "1.0.0"
